config/routes.rb
Rails.application.routes.draw do
  concern :paginatable do
    get '(page/:page)', :action => :index, :on => :collection, :as => ''
  end

  resources :stories, :concerns => :paginatable, only: [ :index, :show ]
  resources :top_hits, :concerns => :paginatable, only: :index

  resources :search_stories

  root "stories_front_page#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search_story.rb
class SearchStory < ActiveType::Object
  
  attribute :id, :integer
  attribute :hn_id, :integer
  attribute :description, :text
  attribute :time_at_num_one, :integer
  attribute :date_seen, :time
  attribute :href, :text

  def self.search_description(search_string)
    Story.where(search_text(search_string)).map do |r|
      new(id: r.id, hn_id: r.hn_id, description: r.description, href: r.href,
          time_at_num_one: r.time_at_num_one, date_seen: r.top_hit.date_seen.to_time)
    end
  end

  def self.search_description_order_by_time_at_num_one(search_string, direction=:desc)
    run_search_query(search_string, "time_at_num_one", direction)
  end

  def self.search_description_order_by_date_seen(search_string, direction=:desc)
    run_search_query(search_string, "date_seen", direction)
  end

  private

  def self.run_search_query(search_string, order_column_name, order_direction)
    order_direction = check_direction(order_direction)
    query = <<-SQL
      with
      s as (select id, hn_id, href, description, time_at_num_one from stories where #{search_text(search_string)}),
      t as (select * from (select top_hits.story_id, top_hits.date_seen, rank() over (partition by story_id order by date_seen desc) from top_hits) subquery where rank = 1)
      select s.id, s.hn_id, s.description, s.time_at_num_one, s.href, t.date_seen from s join t on s.id = t.story_id
      order by #{order_column_name} #{order_direction.to_s}
    SQL
    Story.connection.exec_query(sanitize_sql(query)).map do |r|
      new(id: r["id"], hn_id: r["hn_id"], description: r["description"],
          time_at_num_one: r["time_at_num_one"], date_seen: r["date_seen"],
          href: r["href"])
    end
  end

  def self.check_direction(direction)
    [:desc, :asc].include?(direction) ? direction : :desc
  end

  def self.search_text(search_string="nothing")
    "description ~* '\\m#{search_string}\\M'"
  end

end

app/models/story.rb
class Story < ApplicationRecord

  has_many :top_hits, dependent: :destroy

  validates :hn_id, numericality: { only_integer: true }
  validates :time_at_num_one, numericality: { only_integer: true }
  validates :href, presence: true
  validates :description, presence: true
  validates_uniqueness_of :hn_id

  #scope :last_seen, -> (direction) { order(updated_at: direction) }
  scope :last_seen, -> { order(updated_at: :desc) }
  scope :most_time_at_number_one, -> { order(time_at_num_one: :desc) }

  scope :by_most_time, -> { order(time_at_num_one: :desc).limit(15) }
  scope :newer_than_days, ->(days) { where('updated_at > ?', days).by_most_time }
  scope :last_week, -> { newer_than_days(1.week.ago) }
  scope :last_month, -> { newer_than_days(1.month.ago) }
  scope :all_time, -> { by_most_time }

  scope :time_at_num_one, -> (direction) { order(time_at_num_one: direction) }

  def top_hit
    TopHit.top_hit(self).first
  end

  def self.process(hn_id:, date:, href:, description:)
    story = Story.find_or_create_by!(hn_id: hn_id) do |r|
      r.href = href.blank? ? HackerNews.build_hacker_news_href(hn_id) : href
      r.description = description
    end
    story.description = description if story.description != description
    story.time_at_num_one += 1
    story.save!
    story
  end

  def self.get_ordered_num_one_stories time_frame
    case time_frame
    when nil, 'week'
      Story.last_week
    when 'month'
      Story.last_month
    when 'alltime'
      Story.all_time
    else
      Story.last_week
    end
  end

end

app/models/top_hit.rb
class TopHit < ApplicationRecord
  belongs_to :story

  validates :date_seen, presence: true, date: { after: Proc.new { Time.new(1900) } }
  validates :story_id, numericality: { integer_only: true } 

  scope :recent_top_hits, -> {
    select('*')
    .from("(select *, rank() over (partition by story_id order by date_seen desc) from top_hits) subquery")
    .where("rank = 1")
    .order("date_seen desc")
  }

  scope :get_recent_top_hits, -> { recent_top_hits.limit(10) }

  scope :top_hit, ->(story) { recent_top_hits.where("story_id = ?", story.id) }

  def self.current_top_hit
    # returns nil instead of activerecord::relation
    order(date_seen: :desc).limit(1).first
  end

  def self.new_story_at_top(story_id)
    top_hit = TopHit.current_top_hit
    (top_hit == nil || top_hit.story_id != story_id) ? true : false
  end

  # process_latest_top_story story_id, date
  # story_id is the id from the Story table of the currrently tophit on HN
  #
  def self.process_latest_top_story(story_id:, date:)
    if new_story_at_top(story_id)
      create!(story_id: story_id, date_seen: date)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/search_stories_controller.rb
class SearchStoriesController < ApplicationController
  before_action :search_params, only: :index

  def index
    @search_story = SearchStoryForm.new(search_string: @search_string, order_column_name: @order_column_name, order_direction: @order_direction)
    @stories = @search_story.fulfill
    logger.debug @stories.inspect
  end

  private

  def search_params
    @search_string = params.require(:search_string)
    @order_column_name = params.require(:order_column_name)
    @order_direction = params.require(:order_direction)
    sanitise_search_string
  rescue ActionController::ParameterMissing => e
    redirect_to "/"
  end

  def sanitise_search_string
    @search_string.gsub!(/[^[[:alnum:]]]/,'')
  end

end

app/controllers/show_top_hits_controller.rb
class ShowTopHitsController < ApplicationController

  def show
    @top_hits = TopHit.recent_top_hits.page(params[:page])
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.by_most_time.page(params[:page])
    @search_story = SearchStoryForm.new
  end

  def show
    @story = Story.find(params[:id])
  end

end

app/controllers/stories_front_page_controller.rb
class StoriesFrontPageController < ApplicationController

  def index
    @top_hits = TopHit.get_recent_top_hits
    @stories = Story.get_ordered_num_one_stories(params[:time_frame] || 'week')
    @search_story = SearchStoryForm.new
  end

end

app/controllers/top_hits_controller.rb
class TopHitsController < ApplicationController

  def index
    @top_hits = TopHit.recent_top_hits.page(params[:page])
    @search_story = SearchStoryForm.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def build_hacker_news_href hn_id
    HackerNews.build_hacker_news_href(hn_id)
  end

  def time_difference_between_now_and_date_last_num_one_in_minutes date
    HackerNews.time_difference_between_now_and_date_last_num_one_in_minutes(date)
  end

  def minutes_to_words(minutes)
    minutes = Integer(minutes)
    minutes = 1 if minutes == 0
    hour = 60
    day = hour * 24
    month = Integer(day * 30.4)
    year = Integer(12 * month)
    if minutes < hour
      "#{minutes} #{plural?("min", minutes)}"
    elsif minutes < day
      hours = (minutes/hour).to_i
      "#{hours} #{plural?("hour", hours)}"
    elsif minutes < month
      days = (minutes/day).to_i
      "#{days} #{plural?("day", days)}"
    elsif minutes < year
      months = (minutes/month).to_i
      "#{months} #{plural?("month", months)}"
    else
      years = (minutes/year).to_i
      "#{years} #{plural?("year", years)}"
    end
  end

  def plural? units, value
    value.to_i == 1 ? units : "#{units}s"
  end

end

app/helpers/search_stories_helper.rb
module SearchStoriesHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}/
    %meta{name: "description", content: "Only trending stories from Hacker News"}/
    %meta{property: "og:url", content: "http://hntophits.net"}/
    %meta{property: "og:title", content: "Hacker News Top Stories"}/
    %meta{property: "og:description", content: "Only trending stories from Hacker News"}/
    %title HNTopHits
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'google-analytics'
    = csrf_meta_tags
  %body{class: "#{controller_name}_controller"}
    .container
      .jumbotron
        .row
          .col-md-6
            %h1
              = link_to 'Hacker News Top Hits', controller: :stories_front_page
          .col-md-6
            %ul.what-is-info.list-inline
              %li
                = render partial: 'search_stories/form'
              %li
                %a(href='https://github.com/brucewoodward/hntophits') Source code
      = yield

app/views/search_stories/_form.html.haml
.search-box
  = form_tag '/search_stories', method: :get do
    .form-inline
      = search_field_tag :search_string, @search_story.search_string, placeholder: 'Search...'
      = hidden_field_tag :order_direction, @search_story.order_direction
      = hidden_field_tag :order_column_name, @search_story.order_column_name

app/views/search_stories/index.html.haml
.row
  .col-md-12
    - if @stories.empty?
      .text-center
        %p Nothing found.
    - else
      .search-header
        %p
          %span.heading.last-seen
            = link_to "Last Seen", action: :index, order_direction: @search_story.order_direction, search_string: @search_story.search_string, order_column_name: 'last_seen'
          %span.heading.time-at-num-one
            = link_to "Time at #1", action: :index, order_direction: @search_story.order_direction, search_string: @search_story.search_string, order_column_name: 'time_at_num_one'
          %span.heading.description
            Story
      .stories
        - @stories.each do |story|
          %p
            %span.story-time
              %a(href="#{build_hacker_news_href(story.hn_id)}")
                = minutes_to_words(time_difference_between_now_and_date_last_num_one_in_minutes(story.date_seen)) + ' ago'
            %span.story-duration
              %a(href="#{build_hacker_news_href(story.hn_id)}") 
                = minutes_to_words(story.time_at_num_one)
            %span.story-link
              %a(href="#{story.href}") #{story.description}

app/views/show_top_hits/show.html.haml
.row
  .col-md-12
    .stories
      %h2 Recent Top Hits
      %table.table
        - @top_hits.each do |tophit|
          %tr
            = render :partial => 'stories/tophit', :locals => { :tophit => tophit }
    = paginate @top_hits

app/views/stories/_story.html.haml
%p
  %span.story-link
    %a(href="#{story.href}" target='_blank') #{story.description}
  %span.story-duration
    %a(href="#{build_hacker_news_href(story.hn_id)}" target='_blank') 
      = "(#{minutes_to_words(story.time_at_num_one) + (past_tense ? ' ago' : '')} @ #1)"

app/views/stories/_tophit.html.haml
%p
  .story-link
    %a(href="#{tophit.story.href}" target='_blank') #{tophit.story.description}
  .story-time
    %a(href="#{build_hacker_news_href(tophit.story.hn_id)}" target='_blank')
      = "#1, #{minutes_to_words(time_difference_between_now_and_date_last_num_one_in_minutes(tophit.date_seen))} ago, for #{minutes_to_words(tophit.story.time_at_num_one)}"

app/views/stories/index.html.haml
.row
  .col-md-12
    .stories
      %h2 Most time spent at #1
      - @stories.each do |story|
        = render partial: 'stories/story', locals: { story: story, past_tense: false }
    = paginate @stories

app/views/stories/show.html.haml
.row
  .col-md-12
    %p
      Hacker News ID
      %a(href="#{build_hacker_news_href(@story.hn_id)}")
        = @story.hn_id
    %p
      Title
      = @story.description
    %p
      URL
      %a(href="#{@story.href}")
        = @story.href
    %p
      Minutes spent in number one spot:
      = @story.time_at_num_one

app/views/stories_front_page/index.html.haml
.row
  .recent_top_hits
    .col-md-6
      .stories
        %h2
          = link_to 'Top Stories', url_for(top_hits_path)
        - @top_hits.each do |tophit|
          = render partial: 'stories/tophit', locals: { tophit: tophit }
  .loved_stories
    .col-md-6
      .stories
        .row
          %ul.list-inline
            %li
              %h2
                = link_to 'Trending Stories', url_for(stories_path)
            %li.pull-right.time-frame
              %ul.list-inline
                %li.h5{class: ('underlined' if !params.has_key?(:time_frame) || params[:time_frame] == 'week')}
                  = link_to 'Week', controller: 'stories_front_page', action: :index, time_frame: 'week'
                %li.h5{class: ('underlined' if params.has_key?(:time_frame) && params[:time_frame] == 'month')}
                  = link_to 'Month', controller: 'stories_front_page', action: :index, time_frame: 'month'
                %li.h5{class: ('underlined' if params.has_key?(:time_frame) && params[:time_frame] == 'alltime')}
                  = link_to 'All', controller: 'stories_front_page', action: :index, time_frame: 'alltime'
        - @stories.each do |story|
          = render partial: 'stories/story', locals: { story: story, past_tense: false }

app/views/top_hits/index.html.haml
.row
  .col-md-12
    .stories
      %h2 Recent Top Hits
      %table.table
        - @top_hits.each do |tophit|
          %tr
            = render partial: 'stories/tophit', locals: { tophit: tophit }
    = paginate @top_hits